name: Sync Gitee to GitHub

on:
  push:
    branches:
      - master # 监听 Gitee (你的源仓库) 的 master 分支
      - main   # 如果你的 GitHub (目标仓库) 有其他推送，也监听
  workflow_dispatch: # 允许手动触发工作流

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git User Identity # 新增的步骤
        run: |
          git config user.email "actions@github.com" # 你可以替换成自己的邮箱
          git config user.name "GitHub Actions Bot"   # 你可以替换成自己喜欢的名字

      - name: Add Gitee Remote
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/gitee_key
          chmod 600 ~/.ssh/gitee_key
          echo "Host gitee.com" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/gitee_key" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

          git remote add gitee git@gitee.com:shivermin/my-obsidian.git # 确保这里是你的实际 Gitee 仓库地址

      - name: Fetch from Gitee
        run: |
          git fetch gitee --tags

      - name: Sync Gitee Master to GitHub Main
        run: |
          git checkout main
          git pull gitee master --rebase
          git push origin main --force

      - name: Sync Other Branches (Optional)
        run: |
          for branch in $(git branch -r | grep 'gitee/' | sed 's/gitee\///g' | grep -v 'HEAD' | grep -v 'master' | grep -v 'main'); do # 注意增加了对 'main' 的排除
            git checkout -B $branch gitee/$branch
            git push origin $branch --force
          done

      - name: Sync Tags (Optional)
        run: |
          git push origin --tags
