name: Sync My-test to mynote repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo A
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone mynote repo (仓库 B)
        run: |
          git clone git@github.com:shiverminvip/mynote.git repo-b
          cd repo-b
          git checkout main

      - name: Sync My-test/ to repo-b/笔记/Obsidian/
        run: |
          rsync -av --delete ./My-test/ ./repo-b/笔记/Obsidian/

      - name: Commit & Push to repo B
        run: |
          cd repo-b
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add 笔记/Obsidian/
            git commit -m "Sync from Obsidian My-test at ${{ github.sha }}"
            git push origin main
          else
            echo "No changes to commit"
          fi
