name: Sync My-test to mynote repo

on:
  push:
    branches:
      - main
    paths:
      - 'My-test/**'  # 只监听这个目录的变动

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo A
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone mynote repo
        run: |
          git clone git@github.com:shivermin/mynote.git
          cd mynote
          git checkout main

      - name: Sync My-test to mynote/笔记/Obsidian
        run: |
          rsync -av --delete ./My-test/ ./mynote/笔记/Obsidian/

      - name: Commit and push changes
        run: |
          cd mynote
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add 笔记/Obsidian/
            git commit -m "Sync from Obsidian My-test at ${{ github.sha }}"
            git push origin main
          else
            echo "No changes to commit"
          fi
